### ISSUE TITLE
firebase_auth build warnings

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1083]
#37230 related.

```
[00:35:48]: ▸ Compiling FirebaseAuthPlugin.m
[00:35:48]: ▸ ⚠️  /Users/jon/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.14.0+1/ios/Classes/FirebaseAuthPlugin.m:161:40: incompatible pointer to integer conversion assigning to 'BOOL' (aka 'signed char') from 'id _Nullable' [-Wint-conversion]
[00:35:48]: ▸ actionCodeSettings.handleCodeInApp = call.arguments[@"handleCodeInApp"];
[00:35:48]: ▸                                                                         ~~~   ^~~~~~~~~~
[00:35:48]: ▸ ⚠️  /Users/jon/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.14.0+1/ios/Classes/FirebaseAuthPlugin.m:164:47: incompatible pointer to integer conversion sending 'id _Nullable' to parameter of type 'BOOL' (aka 'signed char') [-Wint-conversion]
[00:35:48]: ▸ installIfNotAvailable:call.arguments[@"androidInstallIfNotAvailable"]
[00:35:48]: ▸                                        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[00:35:48]: ▸ ⚠️  /Users/jon/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.14.0+1/ios/Classes/FirebaseAuthPlugin.m:204:10: incompatible pointer to integer conversion initializing 'BOOL' (aka 'signed char') with an expression of type 'id _Nullable' [-Wint-conversion]
[00:35:48]: ▸ BOOL refresh = [args objectForKey:@"refresh"];
[00:35:48]: ▸                                       ^
[00:35:48]: ▸ ⚠️  /Users/jon/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.14.0+1/ios/Classes/FirebaseAuthPlugin.m:72:1: conflicting return type in implementation of 'application:didReceiveRemoteNotification:fetchCompletionHandler:': 'BOOL' (aka 'signed char') vs 'bool' [-Wmismatched-return-types]
[00:35:48]: ▸ - (bool)application:(UIApplication *)application
[00:35:48]: ▸          ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[00:35:48]: ▸ Compiling firebase_auth-dummy.m
[00:35:48]: ▸ Compiling FirebaseAuthPlugin.m
[00:35:48]: ▸ ⚠️  /Users/jon/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.14.0+1/ios/Classes/FirebaseAuthPlugin.m:220:63: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
[00:35:48]: ▸ [NSNumber numberWithInt:expirationTimestamp],
[00:35:48]: ▸ ^  ~~~~
[00:35:48]: ▸ ⚠️  /Users/jon/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.14.0+1/ios/Classes/FirebaseAuthPlugin.m:221:78: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
[00:35:48]: ▸ @"authTimestamp" : [NSNumber numberWithInt:authTimestamp],
[00:35:48]: ▸                                       ~                       ^~~~~~~~~~~~~~~~~~~
[00:35:48]: ▸ ⚠️  /Users/jon/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.14.0+1/ios/Classes/FirebaseAuthPlugin.m:222:82: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
[00:35:48]: ▸ @"issuedAtTimestamp" : [NSNumber numberWithInt:issuedAtTimestamp],
[00:35:48]: ▸                                                      ~                       ^~~~~~~~~~~~~
```

**Comment by kroikie** [comment]
@lookfirst

The issue at https://github.com/flutter/flutter/issues/38331 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by lookfirst** [comment]
There is some different deprecated warnings now. This can probably be closed.

**Comment by tommyzed** [comment]
I'm still seeing these errors locally. Why was this closed? Do the errors go away with a specific flag? Did some code change fix them?

thx,
tom

**Comment by BondarenkoStas** [comment]
@lookfirst what did you change to get rid of these warnings? @tommyzed I closed because was thinking that specifically this issue is solved.

**Comment by lookfirst** [comment]
The warnings I see are in another issue now... #1087

**Comment by lookfirst** [comment]
which is marked as invalid, but it isn't. =(

**Comment by BondarenkoStas** [comment]
Ok, then I'm closing it now. 
There is a small difference between "bug" and "invalid". Invalid means something doesn't seem right, which is not a bug, but rather different or undesired behaviour. But you are right, that rather confuses people than helps to triage, I changed.

**Comment by rfitz123** [comment]
I am still getting the original errors and it is preventing me from building.

**Comment by KittuPatel** [comment]
I'm getting the same error messages. how should i fix it?

**Comment by andvarp** [comment]
I'm having the same problem in my build. What is the best way to solve this?

**Comment by oakstair** [comment]
Same here!
