### ISSUE TITLE
[Firebase messaging] Deprecated API usage or overrides warning

### ISSUE THREAD

**Issue by kunalpowar** [FirebaseExtended/flutterfire#122]
With `firebase_core: ^0.4.0+9` and  `firebase_messaging: ^5.1.5` as dependancies, Am getting the following warnings on build.

><flutter_path>/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-5.1.5/android/src/main/java/io/flutter/plugins/firebasemessaging/FlutterFirebaseMessagingService.java uses or overrides a deprecated API.

and 

><flutter_path>/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-5.1.5/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java uses unchecked or unsafe operations.

**Comment by fauzipadlaw** [comment]
i use this in pubspec.yml
```
firebase_messaging: 
    git:
      url: git://github.com/FirebaseExtended/flutterfire.git
      ref: 3ab5cc0d3767860d3c6d4c46aee84c7b31965172
      path: packages/firebase_messaging
```
it fixes `/FlutterFirebaseMessagingService.java uses or overrides a deprecated API.` but not `/FirebaseMessagingPlugin.java uses unchecked or unsafe operations.`

#136

**Comment by ashutoshkmr** [comment]
@fauzipadlaw the `/FirebaseMessagingPlugin.java uses unchecked or unsafe operations`. fix has been pushed 
ref : c0f8aa0e3178b2b7a44f2da2ebb2e768c51d3c21

**Comment by fauzipadlaw** [comment]
@ashutoshkmr though it's just suppressing the warning, thank you so much! I hate warnings!

**Comment by kunalpowar** [comment]
@ashutoshkmr will close this issue once your PR is merged then! Thanks for the PR.

**Comment by ashutoshkmr** [comment]
> @ashutoshkmr though it's just suppressing the warning, thank you so much! I hate warnings!

Its actually a false warning, the value sent from dart code is of type int but its serialized hence it is type casted on native side which says its unsafe

**Comment by atakanyildirim** [comment]
I have the same problem. But i didn't fix the problem.

`Note: C:\Users\ASUS\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_messaging-5.1.5\android\src\main\java\io\flutter\plugins\firebasemessaging\FlutterFirebaseMessagingService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\ASUS\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_messaging-5.1.5\android\src\main\java\io\flutter\plugins\firebasemessaging\FirebaseMessagingPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.`

**Comment by ashutoshkmr** [comment]
> I have the same problem. But i didn't fix the problem.
> 
> `Note: C:\Users\ASUS\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_messaging-5.1.5\android\src\main\java\io\flutter\plugins\firebasemessaging\FlutterFirebaseMessagingService.java uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: C:\Users\ASUS\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_messaging-5.1.5\android\src\main\java\io\flutter\plugins\firebasemessaging\FirebaseMessagingPlugin.java uses unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details.`

The PR hasn't  merged yet 
for now you can use this
`firebase_messaging: 
    git:
      url: git://github.com/FirebaseExtended/flutterfire.git
      ref: c0f8aa0e3178b2b7a44f2da2ebb2e768c51d3c21
      path: packages/firebase_messaging
`
or wait for the PR to merge

**Comment by atakanyildirim** [comment]
> > I have the same problem. But i didn't fix the problem.
> > `Note: C:\Users\ASUS\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_messaging-5.1.5\android\src\main\java\io\flutter\plugins\firebasemessaging\FlutterFirebaseMessagingService.java uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: C:\Users\ASUS\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_messaging-5.1.5\android\src\main\java\io\flutter\plugins\firebasemessaging\FirebaseMessagingPlugin.java uses unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details.`
> 
> The PR hasn't merged yet
> for now you can use this
> `firebase_messaging: git: url: git://github.com/FirebaseExtended/flutterfire.git ref: c0f8aa0e3178b2b7a44f2da2ebb2e768c51d3c21 path: packages/firebase_messaging `
> or wait for the PR to merge

It works for debug mode but it's not working for flutter build apk

![Ekran Alıntısı](https://user-images.githubusercontent.com/7900816/64958411-c186a980-d897-11e9-9574-0969443280c5.JPG)

**Comment by atakanyildirim** [comment]
Solution => [https://stackoverflow.com/a/55399559](url)

**Comment by ashutoshkmr** [comment]
> @ashutoshkmr I'll close this issue once your PR is merged then! Thanks for the PR.

The Pr is merge . You can close this issue now :)
