### ISSUE TITLE
🐛 cloud_firestore:Not installing

### ISSUE THREAD

**Issue by IDONTSUDO** [FirebaseExtended/flutterfire#3727]
## Bug report
 

Not installed, cloud_firestore

### Actions to play

1. I can throw the code on the git, I don't think it's necessary.

### Expected behavior

Installing cloud_firestore
### ERORRS

Running "flutter pub get" in chat_...                           
The current Flutter SDK version is 0.0.0-unknown.

Because flutter_complete_guide depends on cloud_firestore >=0.3.0 which requires Flutter SDK version >=0.1.4 <2.0.0, version solving failed.
pub get failed (1; Because flutter_complete_guide depends on cloud_firestore >=0.3.0 which requires Flutter SDK version >=0.1.4 <2.0.0, version solving failed.)
exit code 1

### Doctor of Flutter

Run `flutter doctor` and paste the result below:

<details> <summary>

 </summary>

`` ''
idontsudo@idontsudo:~/flutter/chat_$ flutter doctor
fatal: не найден git репозиторий (или один из родительских каталогов): .git
Doctor summary (to see all details, run flutter doctor -v):
Failed to find the latest git commit date: VersionCheckError: Command exited
with code 128: git -c log.showSignature=false log -n 1 --pretty=format:%ad
--date=iso
Standard out: 
Standard error: fatal: не найден git репозиторий (или один из родительских
каталогов): .git

Returning 1970-01-01 03:00:00.000 instead.
[✓] Flutter (Channel unknown, 0.0.0-unknown, on Linux, locale ru_RU.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.49.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

`` ''

</details>

---

### Flutter dependencies

Run `flutter pub deps - --style = compact` and paste the result below:

<details> <summary> Click to Expand </summary>

`` ''
 name: flutter_complete_guide
description: A new Flutter project.

version: 1.0.0+1

 
 

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  firebase_core: ^0.3.4
  firebase_auth: ^0.8.4+5
  cloud_firestore: ^0.9.13+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
`` ''

</details>

**Comment by Ehesp** [comment]
https://github.com/FirebaseExtended/flutterfire/pull/3713

**Comment by IDONTSUDO** [comment]
@Ehesp  So I need to keep track of this PR, and after it's resolved everything will be fine?

**Comment by Ehesp** [comment]
We recently did some work on automated releases (since manually takes a lot of time) however it seems as though there is a bug which is being looked into.

**Comment by IDONTSUDO** [comment]
@Ehesp  I close the appeal then, I will track your PR, good luck!

**Comment by Ehesp** [comment]
This could actually be unrelated:

```
[✓] Flutter (Channel unknown, 0.0.0-unknown, on Linux, locale ru_RU.UTF-8)
```

How come your flutter version is unknown? Might be causing the problem.

**Comment by Akora-IngDKB** [comment]
@IDONTSUDO 
The problem might not be related. 
Try out the solution [here](https://github.com/flutter/flutter/issues/24956) and [here](https://github.com/flutter/flutter/issues/646990).

**Comment by IDONTSUDO** [comment]
@Ehesp  
Hmm, the problem is I just decided to install
flutter_svg: ^ 0.18.0 and I got the same error.
I thought that if there is a problem, then it should be displayed on other packages, but it was not reproduced on the package
 redux: ^ 4.0.0 + 3 and I can download it and use it.

**Comment by IDONTSUDO** [comment]
@daikini  thx

**Comment by Akora-IngDKB** [comment]
> @Akora-IngDKB thx

Has the problem been resolved?

**Comment by IDONTSUDO** [comment]
@Akora-IngDKB  no, I will open the issue in the flutter repo.

**Comment by IDONTSUDO** [comment]
maybe it has something to do with .git, because every time it gives an error that there is no repository although it is initialized.

```bash
idontsudo @ idontsudo: ~ / flutter / foo $ git --version
git version 2.25.1
```

**Comment by Akora-IngDKB** [comment]
Carefully reinstall Flutter by follow the official [docs](https://flutter.dev/docs/get-started/install).
That should resolve the issue.

If not, then I think this issue will best fit the main flutter [repo](https://github.com/flutter/flutter)

**Comment by Akora-IngDKB** [comment]
> @Akora-IngDKB no, I will open the issue in the flutter repo.

I guess we can close this then.

**Comment by IDONTSUDO** [comment]
@Akora-IngDKB  yes come on, thanks for your help and have a nice day!
```

**Comment by IDONTSUDO** [comment]
hmm a complete reinstallation of Flutter helped me solve the problem with installing flutter_svg: ^ 0.18.0

But cloud_firestore: ^ 0.14.1 is still not installed.


[foo] flutter pub get
Running "flutter pub get" in foo...                             
Because cloud_firestore_web >=0.2.0+1 depends on cloud_firestore_platform_interface >=2.0.1 <2.1.0 and cloud_firestore >=0.14.1 depends on cloud_firestore_platform_interface ^2.1.0, cloud_firestore_web >=0.2.0+1 is incompatible with cloud_firestore >=0.14.1.

So, because foo depends on cloud_firestore ^0.14.1 which depends on cloud_firestore_web ^0.2.0+1, version solving failed.
pub get failed (1; So, because foo depends on cloud_firestore ^0.14.1 which depends on cloud_firestore_web ^0.2.0+1, version solving failed.)
exit code 1

**Comment by Akora-IngDKB** [comment]
I can confirm this problem.
This has to be a problem with the latest cloud_firestore version.

For now, downgrading to `cloud_firestore: ^0.14.0+2` should help.

**Comment by IDONTSUDO** [comment]
and its works!11!

**Comment by dackers86** [comment]
We are currently working on an update for package versioning. 

This can be tracked at https://github.com/invertase/melos/compare/de4e8e0731d6...05ac4241d3e7
