### ISSUE TITLE
Missing BREAKING change for migration guide.

### ISSUE THREAD

**Issue by kevin-induro** [FirebaseExtended/flutterfire#3928]
I've finished up migrating a number of Firebase libraries from their old versions to the new ones. My main focus on the [migration guide page](https://firebase.flutter.dev/docs/migration) was making sure I addressed all the BREAKING issues.

When testing the application, I've noticed a breaking change that is not reported in the documentation: the error codes for Firebase Auth have changed. I discovered this fact through a [Stackoverflow issue](https://stackoverflow.com/a/63958584/1604460) and thought that it should be called out in the documentation.

**Comment by darshankawar** [comment]
@kevin-induro 
There's similar open issue describing your case, [3921](https://github.com/FirebaseExtended/flutterfire/issues/3921).
Please follow-up there for updates. There's also a [comment](https://github.com/FirebaseExtended/flutterfire/issues/3921#issuecomment-712835337) on adding the said breaking change in the change log.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by kevin-induro** [comment]
@darshankawar I appreciate you looking at this, and yes, it looks like the fellow in that issue encountered the same problem I had. Additionally, it's great that enums are being created to cover the codes as right now, I'm relying on my own that I've constructed.

However, this issue was for updating the documentation. Regardless of what happens with the code in the future, we already see that in the past, a BREAKING change has gone through that is not documented in the migration guide. Given that, I believe this is still a relevant issue and not addressed in that.

**Comment by darshankawar** [comment]
@kevin-induro fair enough. reopening.

**Comment by zakariaagha** [comment]
Do we still not have a list of error codes? I can't seem to find them documented anywhere.
