### ISSUE TITLE
🐛 [cloud_firestore_web] Collection get throws Error: [cloud_firestore/unknown] NoSuchMethodError: invalid member on null: 'includeMetadataChanges'

### ISSUE THREAD

**Issue by DelcoigneYves** [FirebaseExtended/flutterfire#4127]
## Bug report

**Describe the bug**
When trying to read data from a collection (either get or snapshot), the following error is thrown:
```
Error: [cloud_firestore/unknown] NoSuchMethodError: invalid member on null: 'includeMetadataChanges'
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:4339:11)
    at collection_reference_web.CollectionReferenceWeb.new.get (http://localhost:5000/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:321:21)
    at get.next (<anonymous>)
    at http://localhost:5000/dart_sdk.js:37679:33
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:37533:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:5000/dart_sdk.js:32507:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:33054:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:33092:17)
    at _Future.new.[_completeWithValue] (http://localhost:5000/dart_sdk.js:32935:23)
```
This does not occur with a single document read. This makes it impossible to use FireStore.

### Steps to reproduce

- Create Firebase project and create sample collection with FireStore
- Try to read it: 
`await _firestore
        .collection('sampleCollection')
        .get();`

### Expected behavior

Data is correctly read.

---

## Additional context

Currently working on v0.18.3, tried reverting to 0.18.0, but encountered the same problem. Reverting to even earlier version results in too many breaking changes.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.18362.1139], locale en-GB)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.6)
[√] VS Code (version 1.51.1)
[√] Connected device (3 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.11.0-213.1.beta
Flutter SDK 1.23.0-18.1.pre

dependencies:
- cloud_firestore 0.14.3 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- crypto 2.1.5 [collection convert typed_data]
- cupertino_icons 1.0.0
- dio 3.0.10 [http_parser path]
- dio_flutter_transformer 3.0.2 [flutter dio]
- enum_to_string 1.0.13
- equatable 1.2.5 [collection meta]
- firebase_auth 0.18.3 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.2 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- get_it 5.0.1 [async meta]
- google_sign_in 4.5.5 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- http 0.12.2 [http_parser path pedantic]
- injectable 1.0.5 [get_it]
- json_annotation 3.1.0
- logger 0.9.4
- pretty_dio_logger 1.1.1 [dio]
- provider 4.3.2+2 [flutter nested collection]
- retrofit 1.3.4+1 [meta dio]
- rxdart 0.24.1
- shared_preferences 0.5.12+2 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- stats 1.0.0 [json_annotation]

dev dependencies:
- build_runner 1.10.3 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner 
term_glyph typed_data]
- injectable_generator 1.0.6 [build source_gen path glob analyzer injectable collection]
- json_serializable 3.5.0 [analyzer build build_config json_annotation meta path source_gen]
- lint 1.3.0
- retrofit_generator 1.4.0 [dio source_gen built_collection code_builder tuple retrofit analyzer dart_style build]

transitive dependencies:
- _fe_analyzer_shared 11.0.0 [meta]
- analyzer 0.40.4 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- build 1.5.0 [analyzer async convert crypto logging meta path glob]
- build_config 0.4.2 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.4 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.4.2 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
- build_runner_core 6.0.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]     
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- checked_yaml 1.0.2 [json_annotation source_span yaml]
- cli_util 0.2.0 [path]
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 2.2.0 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- code_builder 3.5.0 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- dart_style 1.3.8 [analyzer args path source_span]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_auth_platform_interface 2.1.3 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- fixnum 0.10.11
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.2 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- graphs 0.2.0
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- intl 0.16.1 [path]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.3-nullsafety.1
- logging 0.11.4
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.4
- mime 0.9.7
- nested 0.0.4 [flutter]
- node_interop 1.1.1 [js]
- node_io 1.1.1 [node_interop path]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety.1
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.5 [checked_yaml json_annotation pub_semver yaml]
- quiver 2.1.3 [matcher meta]
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+1 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- source_gen 0.9.7+1 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.2 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 0.1.1+2 [json_annotation]
- tuple 1.0.3 [quiver]
- typed_data 1.3.0-nullsafety.3 [collection]
- vector_math 2.1.0-nullsafety.3
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- win32 1.7.3 [ffi]
- xdg_directories 0.1.2 [meta path process]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by fredecodes** [comment]
I am having this issue as well.  Only happens on web (Android and iOS work fine with same code).  Running latest flutter beta (1.23.0-18.1.pre) and Cloud Firestore package (0.14.3).  Also reported today by another user here: https://stackoverflow.com/questions/64843311/flutter-snapshot-data-always-null

**Comment by Altairseven** [comment]
same issue, does anybody has a workarround at this point?

**Comment by fredecodes** [comment]
I switched to the prev versions of the main firebase packages and that fixes the issue.  Now using these 3 versions released on Oct 29:
  firebase_core: 0.5.1
  firebase_auth: 0.18.2
  cloud_firestore: 0.14.2

**Comment by DogeeeXD** [comment]
exactly same issue, only works on Android/iOS, doesn't work on Flutter Web.

**Comment by markusaksli-nc** [comment]
I'm not seeing this with 
```
  firebase_core: ^0.5.2
  cloud_firestore: ^0.14.3
```
on the latest master `1.24.0-8.0.pre.252`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.24.0-8.0.pre.252, on Microsoft Windows [Version 10.0.19041.572], locale et-EE)
    • Flutter version 1.24.0-8.0.pre.252 at C:\Development\flutter_master
    • Framework revision bf2c9dfc05 (32 hours ago), 2020-11-14 22:38:02 -0500
    • Engine revision 3e77d854a7
    • Dart version 2.12.0 (build 2.12.0-45.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\202.7660.26
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (5 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.572]
    • Web Server (web)  • web-server         • web-javascript • Flutter Tools
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 86.0.4240.193
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 86.0.622.68

• No issues found!
```
</details>

Could any of you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) where you also create the test collection with the document(s) that causes the issue?

There are a few document-specific issues out there (for example if the collection contains https://github.com/FirebaseExtended/flutterfire/issues/4103 you will get that error on `.collection().get()`).

**Comment by DelcoigneYves** [comment]
You can reproduce it with the following sample project: https://github.com/DelcoigneYves/firestore-issue

I created a new Firebase project as well, where my firestore database look like this:
![image](https://user-images.githubusercontent.com/14808869/99273565-7f555100-2829-11eb-8397-4cd1c377e994.png)

**Comment by DelcoigneYves** [comment]
Based on @fredecodes ' comment, I played around with the versions a bit, and can confirm the issue does not occur when downgrading firebase_core to 0.5.1. Using this version in combination with cloud_firestore 0.14.3 also works.

**Comment by tapizquent** [comment]
I was getting this same issue. I did not downgrade my firebase core in the `pubspec.yaml`, but instead I replaced the version in my `index.html` and I don't see the error anymore, so I can confirm this is an issue with the latest version of the package.

NOT working: 
```
<script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-analytics.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-firestore.js"></script>
```

Working:
```
<script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-analytics.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-firestore.js"></script>
```

**Comment by markusaksli-nc** [comment]
Reproducible on the latest master `1.24.0-8.0.pre.268` with
`<script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-firestore.js"></script>`
but not with
`<script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-firestore.js"></script>`
(which is still recommended at the [official setup guide](https://firebase.flutter.dev/docs/firestore/overview#3-web-only-add-the-sdk))
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.24.0-8.0.pre.268, on Microsoft Windows [Version 10.0.19041.630], locale et-EE)
    • Flutter version 1.24.0-8.0.pre.268 at C:\Development\flutter_master
    • Framework revision e803b13f01 (30 minutes ago), 2020-11-16 22:55:59 -0800
    • Engine revision f0e80100f7
    • Dart version 2.12.0 (build 2.12.0-49.0.dev)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\202.7660.26
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.630]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 86.0.622.68

• No issues found!
```
</details>

**Comment by mdrideout** [comment]
I am having this issue even when changing firebase-firestore.js to 7.20.0. Currently using the following:
```
  <script src="https://www.gstatic.com/firebasejs/8.1.1/firebase-app.js"></script>
  <script defer src="https://www.gstatic.com/firebasejs/8.1.1/firebase-auth.js"></script>
  <script defer src="https://www.gstatic.com/firebasejs/8.1.1/firebase-firestore.js"></script>
```

**The Function**
```
  Stream<List<Contact>> getAllContactsStream() {
    return _contactsRef
        .orderBy('name', descending: false)
        .snapshots(includeMetadataChanges: true)
        .map((snapshot) => snapshot.docs.map((document) => Contact.fromFirestore(document)).toList());
  }
```

**Error (only on Web, not iOS or Android): **
`Error: [cloud_firestore/unknown] NoSuchMethodError: invalid member on null: 'includeMetadataChanges'`

**Stack: **
```
Stack: dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49      throw_
packages/cloud_firestore_web/src/query_web.dart 161:7                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
dart-sdk/lib/async/async_error.dart 16:24                                         _invokeErrorHandler
dart-sdk/lib/async/stream_pipe.dart 282:9                                         [_handleError]
dart-sdk/lib/async/stream_pipe.dart 161:13                                        [_handleError]
dart-sdk/lib/async/zone.dart 1396:10                                              runBinaryGuarded
dart-sdk/lib/async/stream_impl.dart 376:15                                        sendError
dart-sdk/lib/async/stream_impl.dart 394:16                                        [_sendError]
dart-sdk/lib/async/stream_impl.dart 294:7                                         [_addError]
dart-sdk/lib/async/stream_pipe.dart 132:11                                        [_addError]
dart-sdk/lib/async/stream_pipe.dart 180:7                                         _addErrorWithReplacement
dart-sdk/lib/async/stream_pipe.dart 221:7                                         [_handleData]
dart-sdk/lib/async/stream_pipe.dart 157:13                                        [_handleData]
dart-sdk/lib/async/zone.dart 1384:10                                              runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 357:11                                        [_sendData]
dart-sdk/lib/async/stream_impl.dart 285:7                                         [_add]
dart-sdk/lib/async/broadcast_stream_controller.dart 385:24                        [_sendData]
dart-sdk/lib/async/broadcast_stream_controller.dart 250:5                         add
packages/cloud_firestore_web/src/interop/firestore.dart 283:17                    <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
https://www.gstatic.com/firebasejs/8.1.1/firebase-firestore.js 1:283936           next
https://www.gstatic.com/firebasejs/8.1.1/firebase-firestore.js 1:243227           next
https://www.gstatic.com/firebasejs/8.1.1/firebase-firestore.js 1:225309           <fn>
```

**Doctor Output**
```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-US)
    • Flutter version 1.24.0-10.2.pre at /Users/matt/development/flutter
    • Framework revision 022b333a08 (4 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    • Android SDK at /Users/matt/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554                        • android-x86    • Android 9 (API 28) (emulator)
    • iPhone 12 Pro Max (mobile)   • 2621663E-CFBB-469A-9BD9-44B6D2AF4C14 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • Web Server (web)             • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 86.0.4240.198

• No issues found!
```

**Comment by Levi-Lesches** [comment]
> Notice how I had to replace the version 8.0.2 with 7.20.0 for firebase-firestore.js for it to work properly.

Thanks @tapizquent, this saved me! To clarify, you do not need to change the version in the `pubspec.yaml` for this to work.

**Comment by cmarpert** [comment]
> > Notice how I had to replace the version 8.0.2 with 7.20.0 for firebase-firestore.js for it to work properly.
> 
> Thanks @tapizquent, this saved me! To clarify, you do not need to change the version in the `pubspec.yaml` for this to work.

Thks, helped me, too.
@mdrideout : also had to change the other versions in index.html from 8.1.1 to 8.0.2

**Comment by sunaarun** [comment]
> I was getting this same issue. I did not downgrade my firebase core in the `pubspec.yaml`, but instead I replaced the version in my `index.html` and I don't see the error anymore, so I can confirm this is an issue with the latest version of the package.
> 
> NOT working:
> 
> ```
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-app.js"></script>
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-analytics.js"></script>
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-firestore.js"></script>
> ```
> 
> Working:
> 
> ```
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-app.js"></script>
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-analytics.js"></script>
> <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-firestore.js"></script>
> ```
> 
> Notice how I had to replace the version `8.0.2` with `7.20.0` for `firebase-firestore.js` for it to work properly.
> 
> My `pubspec.yaml` contains the following:
> 
> ```
> firebase_core: ^0.5.2
> cloud_firestore: ^0.14.3
> ```

I was facing the same problem, Thank you for the solution

**Comment by tekno0ryder** [comment]
> I am having this issue even when changing firebase-firestore.js to 7.20.0. Currently using the following:
> 
> ```
>   <script src="https://www.gstatic.com/firebasejs/8.1.1/firebase-app.js"></script>
>   <script defer src="https://www.gstatic.com/firebasejs/8.1.1/firebase-auth.js"></script>
>   <script defer src="https://www.gstatic.com/firebasejs/8.1.1/firebase-firestore.js"></script>
> ```
> 
> **The Function**
> 
> ```
>   Stream<List<Contact>> getAllContactsStream() {
>     return _contactsRef
>         .orderBy('name', descending: false)
>         .snapshots(includeMetadataChanges: true)
>         .map((snapshot) => snapshot.docs.map((document) => Contact.fromFirestore(document)).toList());
>   }
> ```
> 
> **Error (only on Web, not iOS or Android):**
> `Error: [cloud_firestore/unknown] NoSuchMethodError: invalid member on null: 'includeMetadataChanges'`
> 
> **Stack:**
> 
> ```
> Stack: dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49      throw_
> packages/cloud_firestore_web/src/query_web.dart 161:7                             <fn>
> dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
> dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
> dart-sdk/lib/async/async_error.dart 16:24                                         _invokeErrorHandler
> dart-sdk/lib/async/stream_pipe.dart 282:9                                         [_handleError]
> dart-sdk/lib/async/stream_pipe.dart 161:13                                        [_handleError]
> dart-sdk/lib/async/zone.dart 1396:10                                              runBinaryGuarded
> dart-sdk/lib/async/stream_impl.dart 376:15                                        sendError
> dart-sdk/lib/async/stream_impl.dart 394:16                                        [_sendError]
> dart-sdk/lib/async/stream_impl.dart 294:7                                         [_addError]
> dart-sdk/lib/async/stream_pipe.dart 132:11                                        [_addError]
> dart-sdk/lib/async/stream_pipe.dart 180:7                                         _addErrorWithReplacement
> dart-sdk/lib/async/stream_pipe.dart 221:7                                         [_handleData]
> dart-sdk/lib/async/stream_pipe.dart 157:13                                        [_handleData]
> dart-sdk/lib/async/zone.dart 1384:10                                              runUnaryGuarded
> dart-sdk/lib/async/stream_impl.dart 357:11                                        [_sendData]
> dart-sdk/lib/async/stream_impl.dart 285:7                                         [_add]
> dart-sdk/lib/async/broadcast_stream_controller.dart 385:24                        [_sendData]
> dart-sdk/lib/async/broadcast_stream_controller.dart 250:5                         add
> packages/cloud_firestore_web/src/interop/firestore.dart 283:17                    <fn>
> dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
> dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
> https://www.gstatic.com/firebasejs/8.1.1/firebase-firestore.js 1:283936           next
> https://www.gstatic.com/firebasejs/8.1.1/firebase-firestore.js 1:243227           next
> https://www.gstatic.com/firebasejs/8.1.1/firebase-firestore.js 1:225309           <fn>
> ```
> 
> **Pubspec:**
> 
> ```
> dependencies:
>   flutter:
>     sdk: flutter
> 
>   freezed_annotation: ^0.12.0
>   firebase_core: ^0.5.2
>   cloud_firestore: ^0.14.3
>   firebase_auth: ^0.18.3
>   flutter_riverpod: ^0.12.1
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
> 
>   freezed: ^0.12.3
>   json_serializable: ^3.5.0
>   build_runner: ^1.10.6
> ```
> 
> **Doctor Output**
> 
> ```
> [✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-US)
>     • Flutter version 1.24.0-10.2.pre at /Users/matt/development/flutter
>     • Framework revision 022b333a08 (4 days ago), 2020-11-18 11:35:09 -0800
>     • Engine revision 07c1eed46b
>     • Dart version 2.12.0 (build 2.12.0-29.10.beta)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
>     • Android SDK at /Users/matt/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.0-rc2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 12.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.1, Build version 12A7403
>     • CocoaPods version 1.10.0
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
> 
> [✓] VS Code (version 1.51.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.16.0
> 
> [✓] Connected device (4 available)
>     • AOSP on IA Emulator (mobile) • emulator-5554                        • android-x86    • Android 9 (API 28) (emulator)
>     • iPhone 12 Pro Max (mobile)   • 2621663E-CFBB-469A-9BD9-44B6D2AF4C14 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
>     • Web Server (web)             • web-server                           • web-javascript • Flutter Tools
>     • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 86.0.4240.198
> 
> • No issues found!
> ```

Try to change your query to

`List.from(snapshot.docs.map((document) => Contact.fromFirestore(document))
`
instead of toList()

**Comment by AhmedSarhan1999** [comment]
please help me guys i did what you said but i am still having the problem

**Comment by tekno0ryder** [comment]
> please help me guys i did what you said but i am still having the problem

Can you debug your app on mobile?, because web exceptions are misleading, it showed me this exception while I had another problem in my query code

**Comment by jlubeck** [comment]
Having same problem, works on macOS but not on Web using `8.1.2` which I haven't seen mentioned yet

```
  <script src="https://www.gstatic.com/firebasejs/8.1.2/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.1.2/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.1.2/firebase-analytics.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.1.2/firebase-firestore.js"></script>
```

**Comment by rohitkhatri** [comment]
> I was getting this same issue. I did not downgrade my firebase core in the `pubspec.yaml`, but instead I replaced the version in my `index.html` and I don't see the error anymore, so I can confirm this is an issue with the latest version of the package.
> 
> NOT working:
> 
> ```
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-app.js"></script>
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-analytics.js"></script>
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-firestore.js"></script>
> ```
> 
> Working:
> 
> ```
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-app.js"></script>
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-analytics.js"></script>
> <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-firestore.js"></script>
> ```
> 
> Notice how I had to replace the version `8.0.2` with `7.20.0` for `firebase-firestore.js` for it to work properly.
> 
> My `pubspec.yaml` contains the following:
> 
> ```
> firebase_core: ^0.5.2
> cloud_firestore: ^0.14.3
> ```

Working for me, thanks

**Comment by ank237** [comment]
> I was getting this same issue. I did not downgrade my firebase core in the `pubspec.yaml`, but instead I replaced the version in my `index.html` and I don't see the error anymore, so I can confirm this is an issue with the latest version of the package.
> 
> NOT working:
> 
> ```
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-app.js"></script>
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-analytics.js"></script>
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-firestore.js"></script>
> ```
> 
> Working:
> 
> ```
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-app.js"></script>
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-analytics.js"></script>
> <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-firestore.js"></script>
> ```
> 
> Notice how I had to replace the version `8.0.2` with `7.20.0` for `firebase-firestore.js` for it to work properly.
> 
> My `pubspec.yaml` contains the following:
> 
> ```
> firebase_core: ^0.5.2
> cloud_firestore: ^0.14.3
> ```

Thanks a lot.

**Comment by AbhideepChakravarty** [comment]
This is a crappy situation ! I didnt imagine that upgrading the version would kill the app. Had to face a very humiliating situation during a demo. This must be fixed.

**Comment by jocubeit** [comment]
> This is a crappy situation ! I didnt imagine that upgrading the version would kill the app. Had to face a very humiliating situation during a demo. This must be fixed.

Exactly the same situation here. Have since been on a journey to replacing Firestore with an alternative. Very disappointing.

**Comment by tapizquent** [comment]
> > This is a crappy situation ! I didnt imagine that upgrading the version would kill the app. Had to face a very humiliating situation during a demo. This must be fixed.
> 
> 
> 
> Exactly the same situation here. Have since been on a journey to replacing Firestore with an alternative. Very disappointing.

This is indeed a frustrating situation but guys, unfortunately every piece of software had bugs, and just commenting "me too" or "this sucks" doesn't really help the issue.

I am sure the devs are already aware of this and are actively working to fix it.

Please have some patience and try to thumbs-up this issue so it gets more exposure and they can get to fixing it faster. Also, try to go through the code and see if you can help with anything.

I would also recommend NOT doing important presentations right after upgrading without testing that it works first, as you never know what unintended consequences it could have

**Comment by Levi-Lesches** [comment]
Not to mention, version `7.20.0` is the *officially recommended* version. Don't complain because you upgraded, be happy you found the solution and move on. 

This is what is currently on the official [FlutterFire](https://firebase.flutter.dev/docs/firestore/overview) docs: 
![image](https://user-images.githubusercontent.com/20747538/102733572-a234c280-430b-11eb-830a-0014cde7e149.png)

**Comment by ghunkins** [comment]
There are many spots where the current latest version of `8.21.1` is mentioned in official documentation for Javascript web SDK, so it can be frustrating that it doesn't work for Flutter.

I wanted the emulators only available in `>8.0.0` (i.e. `auth` and `firestore`), and the below configuration finally worked for me.

```html
<script src="https://www.gstatic.com/firebasejs/8.2.1/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.1/firebase-analytics.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.1/firebase-auth.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.0.1/firebase-firestore.js"></script>
```
My `pubspec.lock`:
```
firebase_core: ^0.5.3
firebase_analytics: ^6.3.0
firebase_auth: ^0.18.4+1
firebase_storage: ^5.2.0
cloud_firestore: ^0.14.4
```

It looks as though the issue beings with `https://www.gstatic.com/firebasejs/8.0.2/firebase-firestore.js`.

**Comment by Sun3** [comment]
This issue is still happening.

I tested with the latest Firebase:

pubspec.yaml
```
firebase_core: ^0.6.0
firebase_auth: ^0.19.0+1
cloud_firestore: ^0.15.0
```

index.html
```
<script src="https://www.gstatic.com/firebasejs/8.2.2/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.2/firebase-auth.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.2/firebase-firestore.js"></script>
```

Thanks

**Comment by Levi-Lesches** [comment]
> NOT working:
> 
> ```
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-app.js"></script>
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-analytics.js"></script>
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-firestore.js"></script>
> ```
> 
> Working:
> 
> ```
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-app.js"></script>
> <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-analytics.js"></script>
> <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-firestore.js"></script>
> ```
> 
> Notice how I had to replace the version `8.0.2` with `7.20.0` for `firebase-firestore.js` for it to work properly.

See above

**Comment by Sun3** [comment]
@Levi-Lesches Dropping just the firestore version to ```7.20.0``` did work. I hope they fix it soon going forward to work with the latest SDK.

Thanks.

**Comment by mikehardy** [comment]
If 8.0.2 is where it starts https://firebase.google.com/support/release-notes/js
That's 2.0.2 internally https://github.com/firebase/firebase-js-sdk/blame/master/packages/firestore/CHANGELOG.md

May help bisect what exactly changed

**Comment by Levi-Lesches** [comment]
I know nothing about that repository, and not much about browser js code in general, but these look suspicious (from 2.0.2 in the Changelog):
* [`6dffdf2eb`](https://github.com/firebase/firebase-js-sdk/commit/6dffdf2eb1323ec9047af4ed78302a68f7dacce3) [#3594](https://github.com/firebase/firebase-js-sdk/pull/3594) - Merge bundle loading implementation without exposing public API

- [`484e90a1d`](https://github.com/firebase/firebase-js-sdk/commit/484e90a1d8f63e04268ff5bce4e3e0873c56c8e1) [#4043](https://github.com/firebase/firebase-js-sdk/pull/4043) - Internal changes to support upcoming modular API.

**Comment by Yberion** [comment]
Faced that problem as well, thanks for pointing out the "fix".

It would be cool to have some more informations about the problem and at least the doc telling us to not use the latest version of firebase-firestore.js on Flutter Web.

**Comment by Levi-Lesches** [comment]
> This is what is currently on the official [FlutterFire](https://firebase.flutter.dev/docs/firestore/overview) docs:
>
> ![image](https://user-images.githubusercontent.com/20747538/102733572-a234c280-430b-11eb-830a-0014cde7e149.png)

It does.

**Comment by Yberion** [comment]
> > This is what is currently on the official [FlutterFire](https://firebase.flutter.dev/docs/firestore/overview) docs:
> > ![image](https://user-images.githubusercontent.com/20747538/102733572-a234c280-430b-11eb-830a-0014cde7e149.png)
> 
> It does.

It also say `7.20.0` for `firebase-app.js` but the latest version works and in the doc there is no warning about not using the latest version.

**Comment by sscast** [comment]
I got a permission denied error after downgrading, and then realized that when you downgrade to 7.20.0 the emulator is not supported.

**Comment by hayashi-ay** [comment]
Using the version `8.0.1` also works as of reserved hosting URLs.

```html
<body>
    <script src="/__/firebase/8.2.3/firebase-app.js"></script>
    <script src="/__/firebase/8.0.1/firebase-firestore.js"></script>
</body>
```

**Comment by searchy2** [comment]
Reseting to v7.20.0 worked for me. 
Web library versions:
```
<script src="https://www.gstatic.com/firebasejs/8.2.3/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.3/firebase-analytics.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.3/firebase-auth.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-firestore.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.3/firebase-functions.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.3/firebase-storage.js"></script>
```

Flutter versions:
```
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  google_sign_in: ^4.5.9
  cloud_firestore: ^0.16.0
  firebase_database: ^6.0.0
  firebase: ^8.0.0
  cloud_functions: ^0.9.0
```

**Comment by esDotDev** [comment]
Switching down to 8.0.1 fixed the issue. There goes 2 hrs of pointless debugging out the window. come on guys...

**Comment by Ehesp** [comment]
> Switching down to 8.0.1 fixed the issue. There goes 2 hrs of pointless debugging out the window. come on guys...

Not being able to control the versions within the library itself is a problem as you can see. Firebase release new Web SDK versions all the time and we run tests against a fixed version, vs one we control. Right now the docs recommend 7.20.0 because that's what everything is tested against. It takes time to upgrade, fix tests etc.

Following the docs you shouldn't have issues:

![image](https://user-images.githubusercontent.com/842078/106595230-25704780-654b-11eb-8630-d41a7ea0451f.png)

**Comment by genovoxx** [comment]
> Switching down to 8.0.1 fixed the issue. There goes 2 hrs of pointless debugging out the window. come on guys...

You perfectly describe what happens to us. Thanks for the help found here!

**Comment by baylward1762** [comment]
Im still experiencing it i have used 7.20.0 as well but can anyone see if I'm missing something?


`<script src="https://www.gstatic.com/firebasejs/8.2.4/firebase-analytics.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.4/firebase-firestore.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.3/firebase-storage.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.0.1/firebase-firestore.js"></script>`

`  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  firebase: ^8.0.0
  provider: ^4.3.3
  cloud_firestore: ^0.16.0`

**Comment by tmldoc** [comment]
I am facing the error 
"Error: [cloud_firestore/unknown] Expected a value of type '((Object?) => Object)?', but got one of type '(Object) => Object?'"
After migrating to nullsaftey, using in pubspec.yaml versions ^1.0.0 for both firebase core and firestore.

Tried the above solutions in index.html [7.20.0 all the way up to 8.2.10],
The above error always returns from firestore.get() requests or .snapshots.

**Comment by daveparks23** [comment]
> I am facing the error
> "Error: [cloud_firestore/unknown] Expected a value of type '((Object?) => Object)?', but got one of type '(Object) => Object?'"
> After migrating to nullsaftey, using in pubspec.yaml versions ^1.0.0 for both firebase core and firestore.
> 
> Tried the above solutions in index.html [7.20.0 all the way up to 8.2.10],
> The above error always returns from firestore.get() requests or .snapshots.

Have the exact same problem.

**Comment by Levi-Lesches** [comment]
> "Error: [cloud_firestore/unknown] Expected a value of type '((Object?) => Object)?', but got one of type '(Object) => Object?'"

Seems like this might be a Dart-side error, given the nullsafety. Maybe open a new issue? This issue is for version mismatch on the JavaScript side. 

Actually, can this issue be closed? It's caused by an unexpected null, which won't be an issue anymore. @DelcoigneYves @Ehesp

**Comment by tmldoc** [comment]
> > "Error: [cloud_firestore/unknown] Expected a value of type '((Object?) => Object)?', but got one of type '(Object) => Object?'"
> 
> Seems like this might be a Dart-side error, given the nullsafety. Maybe open a new issue? This issue is for version mismatch on the JavaScript side. 
> 
> Actually, can this issue be closed? It's caused by an unexpected null, which won't be an issue anymore. @DelcoigneYves @Ehesp 

You're correct, I'll open up a separate issue for this and track things there. As always, thank you to everybody who is doing an amazing job on these projects, we appreciate everything and all the efforts👌

**Comment by daveparks23** [comment]
> > > "Error: [cloud_firestore/unknown] Expected a value of type '((Object?) => Object)?', but got one of type '(Object) => Object?'"
> > 
> > 
> > Seems like this might be a Dart-side error, given the nullsafety. Maybe open a new issue? This issue is for version mismatch on the JavaScript side.
> > Actually, can this issue be closed? It's caused by an unexpected null, which won't be an issue anymore. @DelcoigneYves @Ehesp
> 
> You're correct, I'll open up a separate issue for this and track things there. As always, thank you to everybody who is doing an amazing job on these projects, we appreciate everything and all the efforts👌

I just created an issue here.
https://github.com/FirebaseExtended/flutterfire/issues/5238 
let me know if I need to delete this or edit it.

**Comment by DelcoigneYves** [comment]
It can indeed be closed, original issue was due to version mismatches, and should be better documented.

**Comment by mikehardy** [comment]
@DelcoigneYves I cannot explain this though? 🤔  https://github.com/FirebaseExtended/flutterfire/runs/2038841939?check_suite_focus=true#step:6:6749

**Comment by tmldoc** [comment]
> > > > "Error: [cloud_firestore/unknown] Expected a value of type '((Object?) => Object)?', but got one of type '(Object) => Object?'"
> > > 
> > > 
> > > Seems like this might be a Dart-side error, given the nullsafety. Maybe open a new issue? This issue is for version mismatch on the JavaScript side.
> > > Actually, can this issue be closed? It's caused by an unexpected null, which won't be an issue anymore. @DelcoigneYves @Ehesp
> > 
> > You're correct, I'll open up a separate issue for this and track things there. As always, thank you to everybody who is doing an amazing job on these projects, we appreciate everything and all the efforts👌
> 
> I just created an issue here.
> https://github.com/FirebaseExtended/flutterfire/issues/5238 
> let me know if I need to delete this or edit it.

Thanks a lot, your post is perfect. I added my two cents and upvoted it there.

**Comment by markusaksli-nc** [comment]
Shouldn't this remain open to track this as a blocker to validating to a newer version of the JS SDK?

**Comment by fredecodes** [comment]
I have updated to the most recent firebase package version, Flutter 2.0 (with null safety not enabled), and am still getting the same exact error that started this post many months ago.  I tried downgrading the javascript version to 7.20 but still getting the error.  Isn't there any known fix at this point?

My packages:
` firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1`
The error:
`[cloud_firestore/unknown] NoSuchMethodError: invalid member on null: 'includeMetadataChanges'`
The generated index.html:
`  <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-firestore.js"></script>`

**Comment by Levi-Lesches** [comment]
Supposedly it's working now: #5050

**Comment by fredecodes** [comment]
No, #5050 is for a completely different error, unrelated to this one:
`Error: Expected a value of type '((Object?) => Object)?', but got one of type '(Object) => Object?`

**Comment by msoham123** [comment]
@fredecodes I fixed this error by running a pub upgrade.

**Comment by Levi-Lesches** [comment]
@fredecodes I asked for confirmation in that issue, but it seems like they are simply using a higher JS version (`8.2.10` I believe) with Dart version `1.0.0` and it worked for them.

**Comment by markusaksli-nc** [comment]
@Levi-Lesches Not sure what you mean but that is a completely unrelated issue and the fix for it was also purely on the dart interop side so it has nothing to do with the JS import version.

**Comment by markusaksli-nc** [comment]
I'm still able to reproduce the issue here with
```yaml
  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.1
```
```html
  <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-firestore.js"></script>
```
and get `[cloud_firestore/unknown] NoSuchMethodError: invalid member on null: 'includeMetadataChanges'` on the latest master `2.1.0-11.0.pre.205`.
<details>
 <summary>flutter doctor -v</summary>

```console
[√] Flutter (Channel master, 2.1.0-11.0.pre.205, on Microsoft Windows [Version 10.0.19041.867], locale et-EE)
    • Flutter version 2.1.0-11.0.pre.205 at C:\Development\flutter_master
    • Framework revision 267f66a7dc (9 hours ago), 2021-03-10 23:15:03 -0500
    • Engine revision 1b68503bc8
    • Dart version 2.13.0 (build 2.13.0-125.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882
    • Flutter plugin version 54.0.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.7148.57
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!
```
</details>

I'm going to reopen this because officially supporting auth emulator and the latest JS SDK features, in general, will be blocked or at least hindered by this.

**Comment by alpha-se** [comment]
I'm still having problems with collection queries because of this.
I traced it down to this line:
https://github.com/FirebaseExtended/flutterfire/blob/6544551ff3ac5665086385aa24f1ff4020a8ca55/packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart#L415

Problem seems to be that jsify is not allowing a nullable but we pass in one here.
Given that the options aren't actually handled anyways just changing to .docChanges(), fixes things for me, but obviously not a good solutions. Would be great if somebody could confirm and find a better solution.

**Comment by devj3ns** [comment]
I am not sure if this belongs in this issue, but I cannot update a document field with a null value in Firebase Firestore since the null safety version.

```
Map<String, Object?> toDocument() {
    return {
      'title': null,
      'text': null,
    };
  }

await _messageCollection.doc(docId).update(message.toDocument());
```

When I change the null's to `''` the code works.

**Comment by arturcava** [comment]
I had the same problem, but it works if you use stream instead of future, like 
Stream<QuerySnapshot> str = firestore.collection("collection").snapshots();
And retrieve the data using a FutureBuilder.

**Comment by cngeru** [comment]
Getting this error in version `8.2.10`.. Any fix ?

**Comment by GerryWong168** [comment]
Same with me but I was using 8.3.1 ... downgrading  firebase-firestore.js in index.html works.  Any fixes?

**Comment by Beautylivery** [comment]
Seems the issue still remains with 8.3.2 ... still running with 7.20

**Comment by mikehardy** [comment]
@Beautylivery if there is no traffic here, the issue will remain. You may also use 8.0.1, it works. The problem begins with 8.0.2

**Comment by Ehesp** [comment]
Ok so as we see [here](https://github.com/firebase/firebase-js-sdk/blob/626c05b36cfe7f91ac9b6aad730c0f04d6bb8c01/packages/firestore/src/exp/snapshot.ts#L445), the code is:

```ts
docChanges(options: SnapshotListenOptions = {}):
```

Passing in `null` is still a value, so `options` is assigned to `null`. The fix is to pass `undefined` through.
