### ISSUE TITLE
FirebaseError: Messaging: This browser doesn't support the API's required to use the firebase SDK. (messaging/unsupported-browser).

### ISSUE THREAD

**Issue by SantyTaco** [FirebaseExtended/flutterfire#4473]
I implemented the FCM in my flutter web project. It works fine in Chrome but in Safari the web application stop working.

Flutter doctor:
```bash
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)
```
```yaml
dependencies added:
firebase_core: "^0.5.3"
firebase_messaging: "^8.0.0-dev.10"
```
The problem is in the moment that I added the dependencies. First start to ask for the initialization, if I initialize it I get this error:
`FirebaseError: Messaging: This browser doesn't support the API's required to use the firebase SDK. (messaging/unsupported-browser).` and the app stops working.

**Comment by TahaTesser** [comment]
Hi @SantyTaco 
The offical example doesn't run on the web because `flutter_local_notifications` 
Can you please provide  a complete reproducible minimal code sample
Thank you

**Comment by SantyTaco** [comment]
Thank you Taha for your answer, the main problem is that we have a flutter mobile app for android and ios. A functionality for ios devices needs to leave from the mobile app to the web app to be completed. The ios devices for default use safari so when we implemented the firebase messaging into the flutter web app in safari the web app does not work. I could reproduce it in the default flutter app. These is the code:
* pubspec.yaml
`name: flutter_web_test
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "^0.5.3"
  firebase_messaging: "^8.0.0-dev.10"


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`
**web/index.html**
`
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter application.">

  
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="flutter_web_test">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>flutter_web_test</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
      });
    }
  </script>
  
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-messaging.js"></script>

  
  <script>
    // Your web app's Firebase configuration
    // For Firebase JS SDK v7.20.0 and later, measurementId is optional
    var firebaseConfig = {
      apiKey: "test key",
      authDomain: "test.firebaseapp.com",
      databaseURL: "https://test.firebaseio.com",
      projectId: "test",
      storageBucket: "test.com",
      messagingSenderId: "testId",
      appId: "testId",
      measurementId: "testId"
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
  </script>
  <script src="main.dart.js" type="application/javascript"></script>
</body>
</html>
`
**main.dart**
`import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`
I used this plug in to implement the FCM into the flutter web, it would be grate that if safari does not support FCM the web app continue working with out messaging.

**Comment by TahaTesser** [comment]
Hi @SantyTaco 
Thanks for filing the issue, providing details, I can reproduce this 

### Preview
<img width="1134" alt="Screenshot 2020-12-29 at 4 54 02 PM" src="https://user-images.githubusercontent.com/48603081/103280503-970e2080-49f6-11eb-8c1c-553acc93f423.png">


```bash
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.3
  firebase_messaging: ^8.0.0-dev.11
  flutter_local_notifications: ^3.0.2
  http: ^0.12.2
```

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.1.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 8f89f6505b (2 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (2 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.3
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

</details>

**Comment by SantyTaco** [comment]
Hi @TahaTesser, very good. I hope it helps to resolve the issue.

**Comment by kmcgill88** [comment]
I ran into this problem too. Downgrading to `firebase_messaging` [8.0.0-dev.9](https://pub.dev/packages/firebase_messaging/versions/8.0.0-dev.11/changelog#800-dev9) seems to be a temp workaround. The release notes state `8.0.0-dev.10` `FEAT: web implementation (#4206).`

**Comment by dineshshanmugam** [comment]
Downgrading doesn't seem to solve the issue for me.
On browsers that does not support messaging the app does not even open but on browsers supporting messaging it loads fine.

Uncaught (in promise) FirebaseError: Messaging: This browser doesn't support the API's required to use the firebase SDK. (messaging/unsupported-browser).
c errors.ts:92
    create errors.ts:128
    <anonymous> index.ts:56
    getOrInitializeService provider.ts:194
    getImmediate provider.ts:95
    _getService firebaseApp.ts:127
    i firebaseNamespaceCore.ts:228
    n firebaseNamespaceCore.ts:209
    getMessagingInstance messaging.dart:20
    new firebase_messaging_web.dart:36
    registerWith firebase_messaging_web.dart:25
    registerPlugins generated_plugin_registrant.dart:25
    main web_entrypoint.dart:14
    runBody async_patch.dart:84
    _async async_patch.dart:123
    main$ web_entrypoint.dart:13
    dartRunMain main_module.bootstrap.js:20
    $dartRunMain main_module.bootstrap.js:19

Any workarounds or fixes would be very helpful.

**Comment by kmcgill88** [comment]
I believe the JS promise rejection is making the Dart side explode on initialization. [firebase_messaging_web.dart](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging_web/lib/firebase_messaging_web.dart#L36) does not check the JS API of [isSupported](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging_web/lib/src/interop/messaging_interop.dart#L14) before getting on its way. 

I'm guessing if `isSupported()` is checked before trying to init messaging on the Dart side would *fix* the issue. However `FirebaseMessaging.instance` would either have to return null or a full no-op implementation of `FirebaseMessagingWeb`. I lean towards the full no-op when a browser isn't supported.

For my use-case, I don't care if this package works on the web but I need it to not explode for any browser. I use Messaging only with mobile platforms. If no one is actively looking into this I'd take a crack at a PR for it.

**Comment by devxpy** [comment]
@dineshshanmugam Downgrading works for me - 

```
firebase_core: ^0.5.3
firebase_messaging: 8.0.0-dev.10
```

**Comment by arsamme** [comment]
> I believe the JS promise rejection is making the Dart side explode on initialization. [firebase_messaging_web.dart](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging_web/lib/firebase_messaging_web.dart#L36) does not check the JS API of [isSupported](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging_web/lib/src/interop/messaging_interop.dart#L14) before getting on its way.
> 
> I'm guessing if `isSupported()` is checked before trying to init messaging on the Dart side would _fix_ the issue. However `FirebaseMessaging.instance` would either have to return null or a full no-op implementation of `FirebaseMessagingWeb`. I lean towards the full no-op when a browser isn't supported.
> 
> For my use-case, I don't care if this package works on the web but I need it to not explode for any browser. I use Messaging only with mobile platforms. If no one is actively looking into this I'd take a crack at a PR for it.

Would you do this favor?

**Comment by dineshshanmugam** [comment]
> @dineshshanmugam Downgrading works for me -
> 
> ```
> firebase_core: ^0.5.3
> firebase_messaging: 8.0.0-dev.10
> ```


i updated to firebase_messaging: "8.0.0-dev.9" and this seems to work  for some reason dev.10 doesn't seem to do the trick.

**Comment by kmcgill88** [comment]
Anyone following, check out this PR https://github.com/FirebaseExtended/flutterfire/pull/4644 for a local work around if you can't wait for this to be merged.

**Comment by kmcgill88** [comment]
This fix is included in [8.0.0-dev.14](https://pub.dev/packages/firebase_messaging/versions/8.0.0-dev.14/install) even though the release notes don't mention it

**Comment by Salakar** [comment]
> This fix is included in [8.0.0-dev.14](https://pub.dev/packages/firebase_messaging/versions/8.0.0-dev.14/install) even though the release notes don't mention it

It is mentioned in the web packages changelog - https://pub.dev/packages/firebase_messaging_web/changelog#010-dev5 - but yes this has shipped :)

**Comment by kmcgill88** [comment]
Ooohh...my bad missed that. Thank you!

**Comment by Andranjo97** [comment]
Yes, currently working in 8.0.0-dev.14. Thank you guys!
