### ISSUE TITLE
🐛 [firebase_ml_custom] Could not find com.google.firebase:firebase-ml-model-interpreter or Firebase/MLModelInterpreter

### ISSUE THREAD

**Issue by supratikkoley** [FirebaseExtended/flutterfire#6298]
## Bug report
Build failed with exception:

FAILURE: Build failed with an exception.
[   +8 ms] * What went wrong:
[  +42 ms] Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
[   +2 ms] > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
[   +1 ms]    > Could not find com.google.firebase:firebase-ml-model-interpreter:.
[   +2 ms]      Required by:
[   +1 ms]          project :app > project :firebase_ml_custom
[   +2 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.
[   +2 ms] * Get more help at https://help.gradle.org
[   +2 ms] BUILD FAILED in 

### Expected behavior
It should fetch the interpreter.

## Additional context
I am using this plugins -

cupertino_icons: ^1.0.0
  firebase_auth: ^1.2.0
  firebase_core: null
  google_sign_in: null
  flutter_time_picker_spinner: null
  syncfusion_flutter_datepicker: null
  weekday_selector: null
  multi_select_item: null
  intl: null
  fluttertoast: null
  sqflite: null
  image_picker: ^0.7.5+3
  path: null
  firebase_storage: ^8.1.0
  multi_image_picker: null
  path_provider: null
  photo_view: null
  shared_preferences: null
  timeago: null
  flutter_facebook_login: null
  flutter_native_timezone: null
  googleapis: null
  googleapis_auth: null
  url_launcher: null
  tflite: ^1.1.2
  firebase_ml_custom: ^0.2.0+1
  camera: ^0.8.0+1
  http: null
  algolia: null
  flutter_credit_card:
    git:
      url: https://github.com/SimformSolutionsPvtLtd/flutter_credit_card.git
  stripe_payment: null
  cloud_functions: #^1.1.0
  firebase_dynamic_links: null
  share: null
  firebase_messaging:
  flutter_local_notifications:
  video_trimmer:
  video_player: null
  video_thumbnail:
  file_picker: null
  swipeable_page_route: null
  rxdart: null
  flutter_web_browser: null
  get:
  fdottedline: ^1.0.1
  cloud_firestore: ^2.2.0

### Flutter doctor

[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.985], locale en-IN)
    • Flutter version 2.2.0 at E:\Flutter\flutter
    • Framework revision b22742018b (3 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\SUPRATIK\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.6
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656

[√] Connected device (3 available)
    • SM A315F (mobile) • RZ8N61GQ3BK • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 90.0.818.51

• No issues found!

**Comment by markusaksli-nc** [comment]
This dependency can't be resolved on both android and ios on `firebase_ml_custom: ^0.2.0+1`.
```
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.firebase:firebase-ml-model-interpreter:.
     Required by:
         project :app > project :firebase_ml_custom
```
```
    [!] CocoaPods could not find compatible versions for pod "Firebase/MLModelInterpreter":
      In Podfile:
        firebase_ml_custom (from `.symlinks/plugins/firebase_ml_custom/ios`) was resolved to 0.2.0-1, which depends on
          Firebase/MLModelInterpreter (= 8.0.0)
```

**Comment by anand654** [comment]
i was having the same problem,
by adding firebase-ml-model-interpreter version in 
DEPENDENCIES/firebase_ml_custom/build.gradle 

before
`dependencies {
        api 'com.google.firebase:firebase-ml-model-interpreter'
    }`

edited
`dependencies {
        api 'com.google.firebase:firebase-ml-model-interpreter:22.0.4''
    }`

and clean the build and run

it solved my problem.

**Comment by Theunodb** [comment]
'''
[!] CocoaPods could not find compatible versions for pod "Firebase/MLModelInterpreter":
  In Podfile:
    firebase_ml_custom (from `.symlinks/plugins/firebase_ml_custom/ios`) was resolved to 0.2.0-2, which depends on
      Firebase/MLModelInterpreter (= 8.3.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/MLModelInterpreter (= 8.3.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

'''

**Comment by Theunodb** [comment]
Anyone know of a workaround for iOS?

**Comment by Puspharaj** [comment]
> i was having the same problem, by adding firebase-ml-model-interpreter version in DEPENDENCIES/firebase_ml_custom/build.gradle
> 
> before `dependencies { api 'com.google.firebase:firebase-ml-model-interpreter' }`
> 
> edited `dependencies { api 'com.google.firebase:firebase-ml-model-interpreter:22.0.4'' }`
> 
> and clean the build and run.
> 
> it solved my problem.

Where did you pasted this line of code?

**Comment by Mmisiek** [comment]
This is working solution for Android but iOS will still not compile with flutter_ml_custom. Any suggestions ?

**Comment by Mmisiek** [comment]
Those changes are not working for iOS at least in my case.

**Comment by Theunodb** [comment]
This is the error with the latest firebase packages

```
[!] CocoaPods could not find compatible versions for pod "Firebase/MLModelInterpreter":
  In Podfile:
    firebase_ml_custom (from `.symlinks/plugins/firebase_ml_custom/ios`) was resolved to 0.2.0-3, which depends on
      Firebase/MLModelInterpreter (= 8.9.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/MLModelInterpreter (= 8.9.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

```

**Comment by MichalOneNav** [comment]
Can someone fix it PLEASE !!!

**Comment by Mmisiek** [comment]
Still same issue, I can't use firebase_ml_custom plugin on iOS, anyone has any ideas how to work around it ?

    [!] CocoaPods could not find compatible versions for pod "Firebase/MLModelInterpreter":
      In Podfile:
        firebase_ml_custom (from `.symlinks/plugins/firebase_ml_custom/ios`) was resolved to 0.2.0-3, which depends on
          Firebase/MLModelInterpreter (= 8.7.0)
    None of your spec sources contain a spec satisfying the dependency: `Firebase/MLModelInterpreter (= 8.7.0)`.
    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * mistyped the name or version.
     * not added the source repo that hosts the Podspec to your Podfile.

**Comment by Mmisiek** [comment]
Any chance they will assign someone to fix it ? I am removing ML from iOS app due to this error. Very disappointed.

**Comment by anand654** [comment]
try changing the version in this file , may be it will work, (i don't have mac to test it , )

file path : `depencencies/firebase_ml_custom/ios/firebase_ml_custom.podspec`
`  s.dependency 'Firebase/MLModelInterpreter', firebase_sdk_version`

**Comment by Mmisiek** [comment]
Unfortunately it did not help:

```
michal@Michals-MacBook-Pro~/Development/pest_scope $ flutter run
Running "flutter pub get" in pest_scope...                          3.4s
Launching lib/main.dart on iPhone 13 in debug mode...
Running pod install...                                           1,071ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A firebase_ml_custom
      A tflite_flutter
      A tflite_flutter_helper
      - Flutter
      - background_fetch
      - battery_info
      - camera
      - catcher
      - cloud_firestore
      - connectivity
      - connectivity_plus
      - device_info_plus
      - firebase_auth
      - firebase_core
      - firebase_crashlytics
      - firebase_remote_config
      - firebase_storage
      - flutter_background_geolocation
      - flutter_email_sender
      - flutter_local_notifications
      - flutter_mailer
      - flutter_secure_storage
      - flutter_sound
      - fluttertoast
      - geocoding
      - geolocator_apple
      - image_picker
      - location
      - package_info
      - package_info_plus
      - path_provider_ios
      - permission_handler
      - shared_preferences
      - syncfusion_flutter_pdfviewer
      - url_launcher
      - video_player

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `background_fetch` from `.symlinks/plugins/background_fetch/ios`
    -> Fetching podspec for `battery_info` from `.symlinks/plugins/battery_info/ios`
    -> Fetching podspec for `camera` from `.symlinks/plugins/camera/ios`
    -> Fetching podspec for `catcher` from `.symlinks/plugins/catcher/ios`
    -> Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
    cloud_firestore: Using Firebase SDK version '8.7.0' defined in 'firebase_core'
    -> Fetching podspec for `connectivity` from `.symlinks/plugins/connectivity/ios`
    -> Fetching podspec for `connectivity_plus` from `.symlinks/plugins/connectivity_plus/ios`
    -> Fetching podspec for `device_info_plus` from `.symlinks/plugins/device_info_plus/ios`
    -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
    firebase_auth: Using Firebase SDK version '8.7.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    firebase_core: Using Firebase SDK version '8.7.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_crashlytics` from `.symlinks/plugins/firebase_crashlytics/ios`
    firebase_crashlytics: Using Firebase SDK version '8.7.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_ml_custom` from `.symlinks/plugins/firebase_ml_custom/ios`
    firebase_ml_custom: Using Firebase SDK version '8.7.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_remote_config` from `.symlinks/plugins/firebase_remote_config/ios`
    firebase_remote_config: Using Firebase SDK version '8.7.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_storage` from `.symlinks/plugins/firebase_storage/ios`
    firebase_storage: Using Firebase SDK version '8.7.0' defined in 'firebase_core'
    -> Fetching podspec for `flutter_background_geolocation` from
    `.symlinks/plugins/flutter_background_geolocation/ios`
    -> Fetching podspec for `flutter_email_sender` from `.symlinks/plugins/flutter_email_sender/ios`
    -> Fetching podspec for `flutter_local_notifications` from
    `.symlinks/plugins/flutter_local_notifications/ios`
    -> Fetching podspec for `flutter_mailer` from `.symlinks/plugins/flutter_mailer/ios`
    -> Fetching podspec for `flutter_secure_storage` from `.symlinks/plugins/flutter_secure_storage/ios`
    -> Fetching podspec for `flutter_sound` from `.symlinks/plugins/flutter_sound/ios`
    -> Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios`
    -> Fetching podspec for `geocoding` from `.symlinks/plugins/geocoding/ios`
    -> Fetching podspec for `geolocator_apple` from `.symlinks/plugins/geolocator_apple/ios`
    -> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `location` from `.symlinks/plugins/location/ios`
    -> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
    -> Fetching podspec for `package_info_plus` from `.symlinks/plugins/package_info_plus/ios`
    -> Fetching podspec for `path_provider_ios` from `.symlinks/plugins/path_provider_ios/ios`
    -> Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `syncfusion_flutter_pdfviewer` from
    `.symlinks/plugins/syncfusion_flutter_pdfviewer/ios`
    -> Fetching podspec for `tflite_flutter` from `.symlinks/plugins/tflite_flutter/ios`
    -> Fetching podspec for `tflite_flutter_helper` from `.symlinks/plugins/tflite_flutter_helper/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
    -> Fetching podspec for `video_player` from `.symlinks/plugins/video_player/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed
      in repo update
      CDN: trunk Relative path: all_pods_versions_0_3_5.txt exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.9.1/Firebase.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.7.0/Firebase.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_c_7_9.txt exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/c/7/9/Reachability/3.2/Reachability.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.7.0/Firebase.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.7.0/Firebase.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.7.0/Firebase.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.7.0/Firebase.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_d_1_8.txt exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/d/1/8/CocoaLumberjack/3.7.2/CocoaLumberjack.podspec.json exists! Returning
      local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_1_3_4.txt exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/1/3/4/tau_core/8.3.12/tau_core.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_0_7_e.txt exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/0/7/e/mobile-ffmpeg-audio/4.4/mobile-ffmpeg-audio.podspec.json exists!
      Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_5_1_0.txt exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/5/1/0/Toast/4.0.0/Toast.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.7.0/Firebase.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.7.0/Firebase.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/7/e/mobile-ffmpeg-audio/4.4.LTS/mobile-ffmpeg-audio.podspec.json exists!
      Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.7.0/Firebase.podspec.json exists! Returning local because
      checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "Firebase/MLModelInterpreter":
      In Podfile:
        firebase_ml_custom (from `.symlinks/plugins/firebase_ml_custom/ios`) was resolved to 0.2.0-3, which
        depends on
          Firebase/MLModelInterpreter (= 8.7.0)

    None of your spec sources contain a spec satisfying the dependency: `Firebase/MLModelInterpreter (= 8.7.0)`.

    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * mistyped the name or version.
     * not added the source repo that hosts the Podspec to your Podfile.

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in
    unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1078:in `block in
    resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1076:in
    `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in `block in
    resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update



Error running pod install
Error launching application on iPhone 13.
```

**Comment by anand654** [comment]
did you tried version 22.0.4, just a guess
`s.dependency 'Firebase/MLModelInterpreter', "~> 22.0.4"`

**Comment by Mmisiek** [comment]
I think there is some dependency missing in iOS package. Not sure where MLModelInterpreter should come from:
```
michal@Michals-MacBook-Pro~/Development/pest_scope/ios $ pod install --repo-update
Updating local specs repositories
Analyzing dependencies
cloud_firestore: Using Firebase SDK version '8.7.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '8.7.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '8.7.0' defined in 'firebase_core'
firebase_crashlytics: Using Firebase SDK version '8.7.0' defined in 'firebase_core'
firebase_ml_custom: Using Firebase SDK version '8.7.0' defined in 'firebase_core'
firebase_remote_config: Using Firebase SDK version '8.7.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '8.7.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "Firebase/MLModelInterpreter":
  In Podfile:
    firebase_ml_custom (from `.symlinks/plugins/firebase_ml_custom/ios`) was resolved to 0.2.0-3, which depends on
      Firebase/MLModelInterpreter (= 8.7.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/MLModelInterpreter (= 8.7.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by Mmisiek** [comment]
I found this information which might be useful:
`The MLModelInterpreter library, which provided both a model downloading API and an interface to the TensorFlow Lite interpreter, is deprecated. This page describes how to use the newer MLModelDownloader library along with TensorFlow Lite's native interpreter interface.`

**Comment by supratikkoley** [comment]
I made plugin for ios to solve this issue. This plugin can only download ml model from firebase and can run the model on the image (it only works for image classification problem).

This is the repo of the plugin (I have not yet published it on pub.dev)
[https://github.com/supratikkoley/ml_custom](url)

Please contribute in this repo to  make this plugin more useful.  🙏

**Comment by Ehesp** [comment]
The ML Custom plugin has been deprecated and replaced with ML Model Downloader: https://firebase.flutter.dev/docs/ml-model-downloader/overview

I'll close this issue - the `firebase_ml_custom` plugin won't be updated.
